# Generated by Django 6.0 on 2025-12-29 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("solapi_sms", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="smsverificationcode",
            new_name="solapi_sms__phone_52bd82_idx",
            old_name="solapi_sms_phone_created_idx",
        ),
    ]
